# Generated by Django 4.2.4 on 2023-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Заголовок страницы"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "url",
                    models.URLField(max_length=500, verbose_name="Ссылка на страницу"),
                ),
                (
                    "url_type",
                    models.CharField(
                        choices=[
                            ("website", "website"),
                            ("book", "book"),
                            ("article", "article"),
                            ("music", "music"),
                            ("video", "video"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Тип ссылки",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bookmarks_images",
                        verbose_name="Картинка превью",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_of_change",
                    models.DateTimeField(null=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Закладка",
                "verbose_name_plural": "Закладки",
            },
        ),
        migrations.CreateModel(
            name="BookmarkCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Описание"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_of_change",
                    models.DateTimeField(null=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
    ]
