# Generated by Django 4.2.4 on 2023-08-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="bookmarkcollection",
            name="bookmark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookmarks.bookmark"
            ),
        ),
        migrations.AddField(
            model_name="bookmarkcollection",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookmarks.collection"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="collections",
            field=models.ManyToManyField(
                related_name="bookmarks",
                through="bookmarks.BookmarkCollection",
                to="bookmarks.collection",
                verbose_name="Коллекции",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
    ]
